{% if item.image.startswith('ubuntu') %}
FROM {{ item.image }}
RUN apt-get update && apt-get install -y sudo python3-minimal && rm -rf /var/lib/apt/lists/*
{% elif item.image.startswith('oraclelinux') %}
FROM {{ item.image }}
RUN yum install -y sudo python3 && yum clean all
{% endif %}
