---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install sudo and python on OracleLinux
      raw: |
        if [ -f /etc/oracle-release ]; then
          yum install -y sudo python3
        fi
      register: install_result
      ignore_errors: true

    - name: Install sudo and python on Ubuntu
      raw: |
        if [ -f /etc/lsb-release ]; then
          apt-get update && apt-get install -y sudo python3-minimal
        fi
      register: install_result
      ignore_errors: true

    - name: Force gather facts after installation
      setup:
      when: install_result is not failed
